services:
  auth:
    build: ./auth
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
  fe-nginx:
    build: ./fe-nginx
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - backend
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/18/docker
  